# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cellDist <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE, absolute = FALSE) {
    .Call(`_DREEP_cellDist`, m, ncores, verbose, full, diag, absolute)
}

